//[LO3.7.3.5]
//Food list item construct/model
//Incomplete and unused currently. Will probably need changes made when actually being used
//Intended use is to store just the data of the specific food that is required for the user. All the macros can be taken from the database if required.
//This just stores how much the user had in the day and when looking back

class ListFoodItem {
  Map<String, dynamic> toMap() {
    return {
      'barcode': barcode,
      'category': category,
      'foodName': foodName,
      'foodServings': foodServings,
      'foodServingSize': foodServingSize,
      'foodCalories': foodCalories,
      'kiloJoules': kiloJoules,
      'proteins': proteins,
      'carbs': carbs,
      'fiber': fiber,
      'sugars': sugars,
      'fat': fat,
      'saturatedFat': saturatedFat,
      'polyunsaturatedFat': polyUnsaturatedFat,
      'monounsaturatedFat': monoUnsaturatedFat,
      'transFat': transFat,
      'cholesterol': cholesterol,
      'calcium': calcium,
      'iron': iron,
      'sodium': sodium,
      'zinc': zinc,
      'magnesium': magnesium,
      'potassium': potassium,
      'vitaminA': vitaminA,
      'vitaminB1': vitaminB1,
      'vitaminB2': vitaminB2,
      'vitaminB3': vitaminB3,
      'vitaminB6': vitaminB6,
      'vitaminB9': vitaminB9,
      'vitaminB12': vitaminB12,
      'vitaminC': vitaminC,
      'vitaminD': vitaminD,
      'vitaminE': vitaminE,
      'vitaminK': vitaminK,
      'omega3': omega3,
      'omega6': omega6,
      'alcohol': alcohol,
      'biotin': biotin,
      'butyricAcid': butyricAcid,
      'caffeine': caffeine,
      'capricAcid': capricAcid,
      'caproicAcid': caproicAcid,
      'caprylicAcid': caprylicAcid,
      'chloride': chloride,
      'chromium': chromium,
      'copper': copper,
      'docosahexaenoicAcid': docosahexaenoicAcid,
      'eicosapentaenoicAcid': eicosapentaenoicAcid,
      'erucicAcid': erucicAcid,
      'fluoride': fluoride,
      'iodine': iodine,
      'manganese': manganese,
      'molybdenum': molybdenum,
      'myristicAcid': myristicAcid,
      'oleicAcid': oleicAcid,
      'palmiticAcid': palmiticAcid,
      'pantothenicAcid': pantothenicAcid,
      'selenium': selenium,
      'stearicAcid': stearicAcid
    };
  }
  ListFoodItem({
    required this.barcode,
    required this.category,
    required this.foodName,
    required this.foodServings,
    required this.foodServingSize,
    required this.foodCalories,
    required this.kiloJoules,
    required this.proteins,
    required this.carbs,
    required this.fiber,
    required this.sugars,
    required this.fat,
    required this.saturatedFat,
    required this.polyUnsaturatedFat,
    required this.monoUnsaturatedFat,
    required this.transFat,
    required this.cholesterol,
    required this.calcium,
    required this.iron,
    required this.sodium,
    required this.zinc,
    required this.magnesium,
    required this.potassium,
    required this.vitaminA,
    required this.vitaminB1,
    required this.vitaminB2,
    required this.vitaminB3,
    required this.vitaminB6,
    required this.vitaminB9,
    required this.vitaminB12,
    required this.vitaminC,
    required this.vitaminD,
    required this.vitaminE,
    required this.vitaminK,
    required this.omega3,
    required this.omega6,
    required this.alcohol,
    required this.biotin,
    required this.butyricAcid,
    required this.caffeine,
    required this.capricAcid,
    required this.caproicAcid,
    required this.caprylicAcid,
    required this.chloride,
    required this.chromium,
    required this.copper,
    required this.docosahexaenoicAcid,
    required this.eicosapentaenoicAcid,
    required this.erucicAcid,
    required this.fluoride,
    required this.iodine,
    required this.manganese,
    required this.molybdenum,
    required this.myristicAcid,
    required this.oleicAcid,
    required this.palmiticAcid,
    required this.pantothenicAcid,
    required this.selenium,
    required this.stearicAcid,
  });

  String barcode;
  String category;
  String foodName;
  String foodServings;
  String foodServingSize;
  String foodCalories;
  String kiloJoules;
  String proteins;
  String carbs;
  String fiber;
  String sugars;
  String fat;
  String saturatedFat;
  String polyUnsaturatedFat;
  String monoUnsaturatedFat;
  String transFat;
  String cholesterol;
  String calcium;
  String iron;
  String sodium;
  String zinc;
  String magnesium;
  String potassium;
  String vitaminA;
  String vitaminB1;
  String vitaminB2;
  String vitaminB3;
  String vitaminB6;
  String vitaminB9;
  String vitaminB12;
  String vitaminC;
  String vitaminD;
  String vitaminE;
  String vitaminK;
  String omega3;
  String omega6;
  String alcohol;
  String biotin;
  String butyricAcid;
  String caffeine;
  String capricAcid;
  String caproicAcid;
  String caprylicAcid;
  String chloride;
  String chromium;
  String copper;
  String docosahexaenoicAcid;
  String eicosapentaenoicAcid;
  String erucicAcid;
  String fluoride;
  String iodine;
  String manganese;
  String molybdenum;
  String myristicAcid;
  String oleicAcid;
  String palmiticAcid;
  String pantothenicAcid;
  String selenium;
  String stearicAcid;

}
